import Navbar from "../../components/Navbar";
import Link from "next/link";
import PortfolioGallery from "../../components/PortfolioGallery";

const images = [
  {src:'/images/events/events/5U8A9700.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_5123.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/4O1A2495.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_4520.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2430.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2231.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/4O1A2478.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_3054.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_0337.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_0321.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_4883.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2228.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/4O1A3379.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2301.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/4O1A3235.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/image0 (3).jpeg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_4325.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2684.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_4895.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2549.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/4O1A3199.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_3648.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_4371.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/image2.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_4521.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_3656.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/4O1A3327.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_4359.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/4O1A3475.jpg',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2916.JPG',alt:'Events photography by Grace Westray'},{src:'/images/events/events/IMG_2282.JPG',alt:'Events photography by Grace Westray'}
];

export default function Page(){return <main className="page-shell"><Navbar/><header className="container portfolio-hero"><div className="eyebrow">Events</div><h1 className="display">Energy, atmosphere, people.</h1><p>Discreet event coverage with an editorial eye — from private celebrations to lively nights and live performance.</p><div className="portfolio-note"><span>Next step</span><span>Tell Grace what you are planning, from an intimate celebration to a full room of energy.</span><a href="/contact">Check availability ↗</a></div></header><section className="container portfolio-gallery-section"><PortfolioGallery images={images}/></section><section className="quote"><div className="container"><small>Next step</small><p>Let's make something worth keeping.</p><Link className="btn btn-solid" href="/contact">Enquire with Grace ↗</Link></div></section></main>}
